# Generated by Django 2.1.5 on 2019-03-12 14:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VariableChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_us.Location')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_us.LocationType')),
            ],
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_us.LocationType')),
            ],
        ),
        migrations.AddField(
            model_name='variablechoices',
            name='variable_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='variable type', chained_model_field='variable type', on_delete=django.db.models.deletion.CASCADE, to='data_us.VariableType'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_us.LocationType'),
        ),
    ]
